### ISSUE TITLE
add python versions to setup

### ISSUE THREAD

**Issue by bwheelz36** [ACRF-Image-X-Institute/SpyGRT#1]
Installation with python3.11 fails.
This is because pyrealsense2 only supports python3.9 or less.
You should add supported python distributions to your setup.py file (google will tell you how)

**Comment by bwheelz36** [comment]
also:
- no need to have dist on github, this just takes up space and adds confusion
- you should add __version__ to your __init__ file and then tell your setup file to read the version from there. This way it is clear what version I am using because I can check spygrt.__version__

**Comment by ybbouchta** [comment]
Added that we require python 3.7, 3.8 or 3.9 and somewhat updated setup.py and __init__.py. 

However, I don't think it's common to be able to check the version with **.version**. You would usually use **spygrt.__version__**. Happy to change it if you can point me to how you would do that :)

**Comment by bwheelz36** [comment]
you've actually already added version in the source, I think it's not in the current release so all good :-)
